[build]
  functions = "netlify/functions"
  publish = "public"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[dev]
  functions = "dist/netlify/functions"
  publish = "public"

[functions]
  included_files = ["**/*.js", "**/*.mjs"]

[[plugins]]
  package = "netlify-plugin-inline-functions-env"

  [plugins.inputs]
    include = ["CLIENTS_CONFIG"]
